{
 "title": "Starling",
 "description": "IoT Central Device Simulator",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Devices Simulated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(starling_simulating_device_total)"
    }
   ]
  },
  {
   "title": "Messages per min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_telemetry_messages_success_total[1m]))"
    }
   ]
  },
  {
   "title": "Data Points per min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_telemetry_datapoints_sent_total[1m]))"
    }
   ]
  },
  {
   "title": "Devices Simulated",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(starling_simulating_device_total) by (model)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Devices Connected",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(starling_simulating_connect_total) by (hub)",
     "legendFormat": "{{hub}}"
    }
   ]
  },
  {
   "title": "Data Points Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(starling_simulating_telemetry_datapoints_sent_total) by (model)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(starling_simulating_telemetry_sent_bytes) by (model)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Provisioning Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_provisioning_success_total[$__range])) by (model)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Devices Connected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(starling_simulating_connect_total)"
    }
   ]
  },
  {
   "title": "Batches per min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_telemetry_batches_success_total[1m]))"
    }
   ]
  },
  {
   "title": "Bytes Sent per min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_telemetry_sent_bytes[1m]))"
    }
   ]
  },
  {
   "title": "Telemetry Batches Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_telemetry_batches_success_total[$__range]))",
     "legendFormat": "Batches Sent"
    }
   ]
  },
  {
   "title": "Telemetry Messages Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_telemetry_messages_success_total[$__range]))",
     "legendFormat": "Messages Sent"
    }
   ]
  },
  {
   "title": "Devices Failed Over",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_failover_total[$__range])) by (model)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Telemetry Message Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_telemetry_messages_failure_total[$__range])) by (error)",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Commands Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_commands_success_total[$__range]))",
     "legendFormat": "Commands Received"
    }
   ]
  },
  {
   "title": "Provisioning Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_provisioning_failure_total[$__range])) by (model)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Telemetry Batches Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_telemetry_batches_success_total[$__range])) by (model)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Telemetry Messages Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_telemetry_messages_success_total[$__range])) by (model)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Connect Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(starling_simulating_connect_latency_seconds_bucket[$__range])) by (le))  ",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(starling_simulating_connect_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(starling_simulating_connect_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(starling_simulating_connect_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Reported Props Updates Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_reported_props_failure_total[$__range])) by (error)",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Reported Props Update Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(starling_simulating_reported_props_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(starling_simulating_reported_props_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(starling_simulating_reported_props_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(starling_simulating_reported_props_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Telemetry Batches Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_telemetry_batches_failure_total[$__range]))",
     "legendFormat": "Batches Send Failures"
    }
   ]
  },
  {
   "title": "Telemetry Batch Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(starling_simulating_telemetry_batch_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(starling_simulating_telemetry_batch_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(starling_simulating_telemetry_batch_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(starling_simulating_telemetry_batch_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Telemetry Message Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(starling_simulating_telemetry_message_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(starling_simulating_telemetry_message_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(starling_simulating_telemetry_message_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(starling_simulating_telemetry_message_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Reported Properties Updates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_reported_props_success_total[$__range]))",
     "legendFormat": "Reported Prop Updates"
    }
   ]
  },
  {
   "title": "Twin Update Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_twin_updates_failure_total[$__range]))",
     "legendFormat": "Twin Update Failures"
    }
   ]
  },
  {
   "title": "Telemetry Batches Skipped",
   "type": "graph",
   "description": "Telemetry batches  are skipped when the device is busy sending another batch. Reduce telemetry interval based on the telemetry batch latency.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_telemetry_batches_skipped_total[$__range]))",
     "legendFormat": "Batches Skipped"
    }
   ]
  },
  {
   "title": "Provisioning Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(starling_provisioning_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(starling_provisioning_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(starling_provisioning_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(starling_provisioning_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Twin Updates Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_twin_updates_success_total[$__range]))",
     "legendFormat": "Twin Updates Sent"
    }
   ]
  },
  {
   "title": "Twin Updates Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(starling_simulating_twin_update_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(starling_simulating_twin_update_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(starling_simulating_twin_update_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(starling_simulating_twin_update_send_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Reported Props Updates Skipped",
   "type": "graph",
   "description": "Reported Props updates are skipped when the device is busy sending another update. Reduce reported props update interval based on the reported props update latency.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starling_simulating_reported_props_skipped_total[$__range]))",
     "legendFormat": "Reported Props Updates Skipped"
    }
   ]
  }
 ]
}